// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6yimRfY9Cq_EQTxo7547b1CD00XCZ5lE',
    appId: '1:63554922604:android:167f6371aa0b93e85f1049',
    messagingSenderId: '63554922604',
    projectId: 'my-first-app-abc6f',
    storageBucket: 'my-first-app-abc6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoxEaFs9IGpgdzc5fKs1t36sn9Rt3WbQQ',
    appId: '1:63554922604:ios:f5602d07d38e41f05f1049',
    messagingSenderId: '63554922604',
    projectId: 'my-first-app-abc6f',
    storageBucket: 'my-first-app-abc6f.firebasestorage.app',
    androidClientId: '63554922604-eovp34fk08ghreggvibnfq7e0dap11hj.apps.googleusercontent.com',
    iosClientId: '63554922604-62e6gg1gm7r0vjqbmi45l73dcc51l014.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3R-wVyxeFHZ2LXEcL1ErGUnhbqZU8fPg',
    appId: '1:63554922604:web:edc345eb9c69bfa75f1049',
    messagingSenderId: '63554922604',
    projectId: 'my-first-app-abc6f',
    authDomain: 'my-first-app-abc6f.firebaseapp.com',
    storageBucket: 'my-first-app-abc6f.firebasestorage.app',
    measurementId: 'G-K9NN4BZGN6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoxEaFs9IGpgdzc5fKs1t36sn9Rt3WbQQ',
    appId: '1:63554922604:ios:f5602d07d38e41f05f1049',
    messagingSenderId: '63554922604',
    projectId: 'my-first-app-abc6f',
    storageBucket: 'my-first-app-abc6f.firebasestorage.app',
    androidClientId: '63554922604-eovp34fk08ghreggvibnfq7e0dap11hj.apps.googleusercontent.com',
    iosClientId: '63554922604-62e6gg1gm7r0vjqbmi45l73dcc51l014.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3R-wVyxeFHZ2LXEcL1ErGUnhbqZU8fPg',
    appId: '1:63554922604:web:edc345eb9c69bfa75f1049',
    messagingSenderId: '63554922604',
    projectId: 'my-first-app-abc6f',
    authDomain: 'my-first-app-abc6f.firebaseapp.com',
    storageBucket: 'my-first-app-abc6f.firebasestorage.app',
    measurementId: 'G-K9NN4BZGN6',
  );

}